name: Deno CI

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Read Deno version from .dvmrc
        id: deno-version
        run: echo "DENO_VERSION=$(cat .dvmrc)" >> $GITHUB_ENV

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}


      - name: Check formatting
        run: deno task fmt:check

      - name: Typescript check
        run: deno task check

      - name: Run unit tests
        run: deno task test

