name: Deno CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'latest'

      - name: Check formatting
        run: deno fmt --check

      - name: Typescript check
        run: deno check

      - name: Run tests
        run: deno test

